FROM ubuntu:latest

COPY ./ansible .

RUN apt update; exit 0
RUN apt install -y python3 \
	&& python3 --version \
	&& apt install -y python3-pip \
	&& pip3 install ansible boto boto3 \
	&& ansible --version \
	&& apt install -y openssh-client \
	&& mkdir ~/.ssh \
	&& echo "StrictHostKeyChecking no" > ~/.ssh/config \
	&& chmod 400 ./presentation.pem \
	&& ansible-playbook ec2_deploy.yml --user ubuntu --key-file presentation.pem
	
	
	
	
