FROM ubuntu:latest

COPY ./ansible .

RUN echo cest
RUN apt update; exit 0
RUN apt install -y python3 \
	&& python3 --version \
	&& apt install -y python3-pip \
	&& pip3 install ansible boto boto3 \
	&& ansible --version
	
	
	
