vse: &vse
  docker:
    - image: circleci/node:8.11.3

version: 2.1
jobs:
  build:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
         root: .
         paths:
            - .
  deploy:
    <<: *vse
    machine:
      enabled: true
    steps:
      - attach_workspace:
         at: .
      - setup_remote_docker:
          docker_layer_caching: false
      # - run:
          # command: ssh "$DOCKER_HOST"
      - run:    # command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
          command: sudo docker build -f "Dockerfile_ubuntu" -t nehehe:latest .
          # command: docker build -f "Dockerfile_ubuntu" -t nehehe:latest .
          # command: docker exec echo
          # command: docker exec -d vse echo blabla
          
  # exececho:
    # <<: *vse
    # steps:
      # - attach_workspace:
         # at: .
      # - run:
          # command: docker exec -d vse echo blabla
                
workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
         requires:
            - build
         # filters:
            # branches:
                # only: master